/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GIU;

import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class Juego_principal extends javax.swing.JFrame {


   private Juego juego;
    

    
    
    public Juego_principal() {
        initComponents();
        setSize(464,554);
        setResizable(false);
        setTitle("Juego");
        setLocationRelativeTo(null);
        this.repaint();
    }

  

   
  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_j1 = new javax.swing.JTextField();
        txt_j2 = new javax.swing.JTextField();
        cmb_color_j1 = new javax.swing.JComboBox<>();
        cmb_color_j2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_modo_juego = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Triquitraque");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 210, 130));

        btn_iniciar.setBackground(new java.awt.Color(0, 102, 102));
        btn_iniciar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciar.setText("Iniciar juego");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 160, 50));

        btn_salir.setBackground(new java.awt.Color(0, 102, 102));
        btn_salir.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 140, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jugador 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jugador 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, -1));

        txt_j1.setBackground(new java.awt.Color(0, 102, 102));
        txt_j1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_j1.setForeground(new java.awt.Color(255, 255, 255));
        txt_j1.setText("Jugador1");
        txt_j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_j1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 90, 30));

        txt_j2.setBackground(new java.awt.Color(0, 102, 102));
        txt_j2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_j2.setForeground(new java.awt.Color(255, 255, 255));
        txt_j2.setText("Jugador2");
        getContentPane().add(txt_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, 30));

        cmb_color_j1.setBackground(new java.awt.Color(0, 102, 102));
        cmb_color_j1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_color_j1.setForeground(new java.awt.Color(255, 255, 255));
        cmb_color_j1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Rojo", "Azul", "Amarillo" }));
        cmb_color_j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_color_j1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_color_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, 30));

        cmb_color_j2.setBackground(new java.awt.Color(0, 102, 102));
        cmb_color_j2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_color_j2.setForeground(new java.awt.Color(255, 255, 255));
        cmb_color_j2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Rojo", "Azul", "Amarillo" }));
        getContentPane().add(cmb_color_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Color:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Color:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 60, -1));

        cmb_modo_juego.setBackground(new java.awt.Color(0, 102, 102));
        cmb_modo_juego.setForeground(new java.awt.Color(255, 255, 255));
        cmb_modo_juego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3X3", "4X4", "5X5" }));
        getContentPane().add(cmb_modo_juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Triquitraque:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 430, 370));

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_color_j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_color_j1ActionPerformed

    }//GEN-LAST:event_cmb_color_j1ActionPerformed

    private void txt_j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_j1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        iniciarJuego();
    }//GEN-LAST:event_btn_iniciarActionPerformed

   
     private void iniciarJuego() {
       
// Obtener los nombres y colores elegidos por el usuario
        String nombreJugador1 = txt_j1.getText();
        String nombreJugador2 = txt_j2.getText();
        String colorJugador1 = cmb_color_j1.getSelectedItem().toString();
        String colorJugador2 = cmb_color_j2.getSelectedItem().toString();
        String modo_juego = cmb_modo_juego.getSelectedItem().toString();

        // Crear una instancia de Juego con los datos recopilados
        Juego juego = new Juego(nombreJugador1, nombreJugador2, colorJugador1, colorJugador2, modo_juego);

        // Crear una instancia de Tablero y pasarle la instancia de Juego
        Tablero tablero = new Tablero(juego);

        // Mostrar el tablero (puedes implementar esto según tu diseño)
        //System.out.println(tablero);
        if (modo_juego=="3X3"){
            Diseño_3x3 tablero3x3 = new Diseño_3x3 (tablero);
      
            tablero3x3.setVisible(true);
        }
        if (modo_juego=="4X4"){
           Diseño_4x4 tablero4x4 = new Diseño_4x4 (tablero);
           tablero4x4.setVisible(true);
        }
        if (modo_juego =="5X5"){
            Diseño_5x5 tablero5x5 = new Diseño_5x5 (tablero);
           tablero5x5.setVisible(true);
        }
         

        // Cerrar la ventana de JuegoPrincipal (opcional)
        this.dispose();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cmb_color_j1;
    private javax.swing.JComboBox<String> cmb_color_j2;
    private javax.swing.JComboBox<String> cmb_modo_juego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_j1;
    private javax.swing.JTextField txt_j2;
    // End of variables declaration//GEN-END:variables
}
